import assert from "node:assert/strict";
import { test } from "node:test";
import MarkdownIt from "markdown-it";
import {
  MAX_BODY_CHARS,
  MAX_LISTED_FILES,
  MAX_TEXT_CHARS,
  MAX_TITLE_CHARS,
  REVIEW_MARKER,
  aiLabel,
  commentBody,
  fingerprintLine,
  INCOMPLETE_LINE,
  postReview,
  reviewBody,
  reviewUrl,
} from "../src/github/review.js";
import { apiFailure, createFakeOctokit } from "./helpers/github-api.js";

const markdown = new MarkdownIt({ html: true, linkify: true, breaks: true });
markdown.linkify.set({ fuzzyLink: false });

const PULL_REQUEST = {
  owner: "octo-org",
  repo: "demo",
  pullNumber: 42,
  headSha: "1".repeat(40),
};

const finding = (overrides = {}) => ({
  path: "src/routes/users.js",
  line: 10,
  severity: "critical",
  category: "security",
  title: "SQL injection in the user search",
  comment: "The name goes into the query text.",
  suggestion: "Pass it as a parameter:\n```js\ndb.query(sql, [name]);\n```",
  ...overrides,
});

// A finding written to break out of the comment: links, images, HTML,
// mentions and a forged marker.
const HOSTILE = finding({
  title: "Title with [a link](https://evil.example) and @octocat",
  comment:
    '<!-- reviewops --> ![x](https://evil.example/p.png) <img src="x"> <details>open</details> #12',
  suggestion: "Visit www.evil.example or mail admin@evil.example",
});

/** The HTML tags the rendered text uses. */
const tagsOf = (text) =>
  new Set(
    [...markdown.render(text).matchAll(/<([a-z0-9]+)/g)].map(
      (match) => match[1],
    ),
  );

const ALLOWED_TAGS = new Set([
  "p",
  "br",
  "code",
  "pre",
  "strong",
  "hr",
  "sub",
  "h3",
  "h4",
  "ul",
  "li",
]);

const selection = ({ inline = [], unplaced = [], overLimit = 0 } = {}) => ({
  inline,
  unplaced,
  dropped: { empty: 0, unknownPath: 0, duplicate: 0, overLimit },
});

const post = (octokit, overrides = {}) =>
  postReview({
    octokit,
    pullRequest: PULL_REQUEST,
    model: "gpt-4.1",
    summaries: ["One query is built from user input."],
    selection: selection({ inline: [finding()] }),
    maxComments: 10,
    skipped: [],
    ...overrides,
  });

// --- commentBody() -------------------------------------------------------------

test("a comment starts with the marker and ends with the AI label", () => {
  const body = commentBody(finding(), "gpt-4.1");

  assert.ok(body.startsWith(`${REVIEW_MARKER}\n`));
  assert.ok(body.endsWith(aiLabel("gpt-4.1")));
  assert.match(body, /AI-generated by ReviewOps \(gpt\\-4\\\.1\)/);
});

test("a comment names severity and category, then title, comment and suggestion", () => {
  const html = markdown.render(commentBody(finding(), "gpt-4.1"));

  assert.match(html, /<strong>🔴 Critical<\/strong> · <code>security<\/code>/);
  assert.match(html, /<strong>SQL injection in the user search<\/strong>/);
  assert.match(html, /The name goes into the query text\./);
  assert.match(html, /<strong>Suggestion<\/strong>/);
  assert.match(
    html,
    /<pre><code class="language-js">db\.query\(sql, \[name\]\);\n<\/code><\/pre>/,
  );
});

test("a comment renders hostile text from the model as text and code only", () => {
  const body = commentBody(HOSTILE, "gpt-4.1");

  for (const tag of tagsOf(body)) assert.ok(ALLOWED_TAGS.has(tag), tag);
  // The marker stands only at the start; the forged one is escaped.
  assert.equal(body.indexOf(REVIEW_MARKER), 0);
  assert.equal(body.lastIndexOf(REVIEW_MARKER), 0);
  assert.match(markdown.render(body), /<code>@octocat<\/code>/);
});

test("a comment puts a title with line breaks on one line", () => {
  const body = commentBody(finding({ title: "First\n\nsecond" }), "gpt-4.1");

  assert.match(body, /^\*\*First second\*\*$/m);
});

test("a comment keeps the marker and the AI label even with very long texts", () => {
  const invisible = String.fromCodePoint(0x200b);
  for (const text of [
    "x".repeat(70000),
    invisible.repeat(70000),
    "`".repeat(70000),
  ]) {
    const body = commentBody(
      finding({ title: text, comment: text, suggestion: text }),
      "gpt-4.1",
    );

    assert.ok(body.length <= MAX_BODY_CHARS, String(body.length));
    assert.ok(body.startsWith(`${REVIEW_MARKER}\n`));
    assert.ok(body.endsWith(aiLabel("gpt-4.1")));
    assert.match(body, /…/);
  }
});

test("a comment cuts long texts at their limits and keeps short ones whole", () => {
  const body = commentBody(
    finding({
      title: "t".repeat(MAX_TITLE_CHARS + 50),
      comment: "c".repeat(MAX_TEXT_CHARS + 50),
      suggestion: "short",
    }),
    "gpt-4.1",
  );

  assert.match(body, new RegExp(`\\*\\*t{${MAX_TITLE_CHARS}}…\\*\\*`));
  assert.match(body, new RegExp(`^c{${MAX_TEXT_CHARS}}…$`, "m"));
  assert.match(body, /^short$/m);
});

test("a comment does not split a character outside the basic plane", () => {
  const emoji = String.fromCodePoint(0x1f600);
  const body = commentBody(
    finding({ comment: "x".repeat(MAX_TEXT_CHARS - 1) + emoji.repeat(10) }),
    "gpt-4.1",
  );

  assert.ok(body.isWellFormed());
});

// --- reviewBody() --------------------------------------------------------------

const bodyWith = (overrides = {}) =>
  reviewBody({
    model: "gpt-4.1",
    summaries: ["One query is built from user input."],
    inline: [finding()],
    listed: [],
    overLimit: 0,
    maxComments: 10,
    skipped: [],
    ...overrides,
  });

test("the review text has the marker, the summary, the counts and the AI label", () => {
  const body = bodyWith({
    inline: [finding(), finding({ severity: "minor", line: 11 })],
  });

  assert.ok(body.startsWith(`${REVIEW_MARKER}\n`));
  assert.match(body, /One query is built from user input\\\./);
  assert.match(
    body,
    /\*\*Findings:\*\* 2 \(1 critical, 0 major, 1 minor, 0 info\)\./,
  );
  assert.ok(body.endsWith(aiLabel("gpt-4.1")));
});

test("the review text lists findings without a line in the diff with their place", () => {
  const body = bodyWith({
    inline: [],
    listed: [finding({ line: 3, path: "src/a.js" })],
  });

  assert.match(body, /#### Findings without a line in the diff/);
  assert.match(body, /· `src\/a\.js`, line 3/);
  assert.match(body, /SQL injection in the user search/);
});

test("the review text counts the findings over max-comments", () => {
  assert.match(
    bodyWith({ overLimit: 4, maxComments: 10 }),
    /4 more findings are not shown \(`max-comments`: 10\)\./,
  );
  assert.doesNotMatch(bodyWith(), /more findings are not shown/);
});

test("the review text lists the first skipped files and counts the rest", () => {
  const skipped = Array.from({ length: MAX_LISTED_FILES + 5 }, (_, index) => ({
    path: `src/file-${index}.js`,
    reason: "the request to the model failed",
  }));

  const body = bodyWith({ skipped });

  assert.match(body, /#### Files not reviewed \(25\)/);
  assert.match(body, /- `src\/file-0\.js`: the request to the model failed/);
  assert.match(body, /- `src\/file-19\.js`/);
  assert.doesNotMatch(body, /src\/file-20\.js/);
  assert.match(body, /- and 5 more files/);
});

test("the review text shows a file name from the pull request as code", () => {
  const body = bodyWith({
    skipped: [{ path: "a`b<img src=x>.js", reason: "excluded" }],
  });

  for (const tag of tagsOf(body)) assert.ok(ALLOWED_TAGS.has(tag), tag);
  assert.match(markdown.render(body), /<code>a`b&lt;img src=x&gt;\.js<\/code>/);
});

test("the review text renders hostile text from the model as text and code only", () => {
  const body = bodyWith({
    summaries: [HOSTILE.comment],
    listed: [HOSTILE],
  });

  for (const tag of tagsOf(body)) assert.ok(ALLOWED_TAGS.has(tag), tag);
  assert.equal(body.lastIndexOf(REVIEW_MARKER), 0);
});

test("after a rejection the review text lists every finding", () => {
  const body = bodyWith({ inline: [], listed: [finding()], fallback: true });

  assert.match(
    body,
    /#### Findings\n\nGitHub did not accept the inline comments/,
  );
});

test("the review text leaves out summaries first, then findings, to fit", () => {
  const long = "word ".repeat(4000);
  const body = bodyWith({
    summaries: Array(20).fill(long),
    inline: [],
    listed: Array.from({ length: 30 }, (_, index) =>
      finding({ line: index + 1, comment: long }),
    ),
  });

  assert.ok(body.length <= MAX_BODY_CHARS, String(body.length));
  assert.match(body, /20 summaries are left out/);
  assert.match(body, /more findings are not shown: they do not fit/);
  assert.ok(body.endsWith(aiLabel("gpt-4.1")));
});

test("the review text stays fast with many summaries and findings", () => {
  const start = performance.now();
  const body = bodyWith({
    summaries: Array(500).fill("A summary of one request. ".repeat(40)),
    inline: [],
    listed: Array.from({ length: 2000 }, (_, index) =>
      finding({ line: index + 1, comment: "word ".repeat(400) }),
    ),
  });

  assert.ok(performance.now() - start < 2000);
  assert.ok(body.length <= MAX_BODY_CHARS);
  assert.ok(body.endsWith(aiLabel("gpt-4.1")));
});

// --- postReview() --------------------------------------------------------------

test("posts one review of the type COMMENT with every inline comment", async () => {
  const octokit = createFakeOctokit();
  const inline = [finding(), finding({ line: 12, severity: "major" })];

  const result = await post(octokit, { selection: selection({ inline }) });

  assert.equal(octokit.reviews.length, 1);
  const [request] = octokit.reviews;
  assert.equal(request.owner, "octo-org");
  assert.equal(request.repo, "demo");
  assert.equal(request.pull_number, 42);
  assert.equal(request.commit_id, PULL_REQUEST.headSha);
  assert.equal(request.event, "COMMENT");
  assert.deepEqual(
    request.comments.map(({ path, line, side }) => ({ path, line, side })),
    [
      { path: "src/routes/users.js", line: 10, side: "RIGHT" },
      { path: "src/routes/users.js", line: 12, side: "RIGHT" },
    ],
  );
  for (const comment of request.comments) {
    assert.ok(comment.body.startsWith(REVIEW_MARKER));
    assert.ok(comment.body.endsWith(aiLabel("gpt-4.1")));
  }
  assert.ok(request.body.startsWith(REVIEW_MARKER));
  assert.deepEqual(result, {
    reviewId: 1000,
    inlineComments: 2,
    fallback: false,
  });
});

test("posts a review without comments when no finding has a line in the diff", async () => {
  const octokit = createFakeOctokit();

  const result = await post(octokit, {
    selection: selection({ unplaced: [finding()] }),
  });

  assert.equal(octokit.reviews.length, 1);
  assert.equal("comments" in octokit.reviews[0], false);
  assert.match(octokit.reviews[0].body, /Findings without a line in the diff/);
  assert.equal(result.inlineComments, 0);
});

test("lists every finding in a second review when GitHub rejects the comments", async () => {
  const octokit = createFakeOctokit([], {
    createReview: (parameters, index) =>
      index === 0 ? apiFailure(422) : { status: 200, data: { id: 77 } },
  });
  const inline = [finding()];
  const unplaced = [finding({ line: 2, title: "Unplaced finding" })];

  const result = await post(octokit, {
    selection: selection({ inline, unplaced }),
  });

  assert.equal(octokit.reviews.length, 2);
  const [, second] = octokit.reviews;
  assert.equal("comments" in second, false);
  assert.equal(second.event, "COMMENT");
  assert.equal(second.commit_id, PULL_REQUEST.headSha);
  assert.match(second.body, /GitHub did not accept the inline comments/);
  assert.match(second.body, /SQL injection in the user search/);
  assert.match(second.body, /Unplaced finding/);
  assert.deepEqual(result, { reviewId: 77, inlineComments: 0, fallback: true });
});

test("fails with the answer of GitHub when the second review is rejected too", async () => {
  const octokit = createFakeOctokit([], {
    createReview: () => apiFailure(422),
  });

  await assert.rejects(
    post(octokit),
    /^Error: GitHub API request failed \(HTTP 422\)\./,
  );
  assert.equal(octokit.reviews.length, 2);
});

test("does not retry a rejected review that had no inline comments", async () => {
  const octokit = createFakeOctokit([], {
    createReview: () => apiFailure(422),
  });

  await assert.rejects(
    post(octokit, { selection: selection({ unplaced: [finding()] }) }),
    /HTTP 422/,
  );
  assert.equal(octokit.reviews.length, 1);
});

test("points at the permission pull-requests: write when GitHub refuses", async () => {
  const octokit = createFakeOctokit([], {
    createReview: () =>
      apiFailure(403, { message: "Resource not accessible by integration" }),
  });

  await assert.rejects(
    post(octokit),
    /HTTP 403\)\. The token may not post a review\. Give the workflow the permission `pull-requests: write` under `permissions`\./,
  );
  assert.equal(octokit.reviews.length, 1);
});

test("names a rate limit instead of the permission", async () => {
  const octokit = createFakeOctokit([], {
    createReview: () =>
      apiFailure(403, { headers: { "x-ratelimit-remaining": "0" } }),
  });

  await assert.rejects(
    post(octokit),
    /HTTP 403\)\. The rate limit of the token/,
  );
});

test("reports no review id when the answer has none", async () => {
  const octokit = createFakeOctokit([], {
    createReview: () => ({ status: 200, data: { id: "not a number" } }),
  });

  assert.equal((await post(octokit)).reviewId, null);
});

test("builds the address of a review from checked values", () => {
  assert.equal(
    reviewUrl("https://github.com", PULL_REQUEST, 77),
    "https://github.com/octo-org/demo/pull/42#pullrequestreview-77",
  );
});

// --- Fingerprints and the range of a review ------------------------------------

const FINGERPRINT = "0123456789abcdef";

test("puts the fingerprint on the second line of an inline comment", () => {
  const body = commentBody(finding(), "gpt-4.1", FINGERPRINT);

  const lines = body.split("\n");
  assert.equal(lines[0], REVIEW_MARKER);
  assert.equal(lines[1], fingerprintLine(FINGERPRINT));
  assert.equal(lines[1], `<!-- reviewops-fingerprint: ${FINGERPRINT} -->`);
  assert.equal(lines[2], "");
  assert.ok(body.endsWith(aiLabel("gpt-4.1")));
});

test("writes no fingerprint line without a fingerprint", () => {
  const body = commentBody(finding(), "gpt-4.1");

  assert.ok(!body.includes("reviewops-fingerprint"));
  assert.ok(body.startsWith(`${REVIEW_MARKER}\n\n`));
});

test("a comment with a fingerprint renders to the same text as one without", () => {
  const strip = (html) =>
    html.replace(/<!--[\s\S]*?-->/g, "").replace(/\s+/g, "");
  assert.equal(
    strip(markdown.render(commentBody(finding(), "gpt-4.1", FINGERPRINT))),
    strip(markdown.render(commentBody(finding(), "gpt-4.1"))),
  );
});

test("text of the model cannot add a fingerprint line", () => {
  const body = commentBody(
    finding({
      comment: `<!-- reviewops-fingerprint: ${FINGERPRINT} -->`,
    }),
    "gpt-4.1",
  );

  assert.ok(!body.includes("reviewops-fingerprint"));
});

test("posts every inline comment with the fingerprint of its line", async () => {
  const octokit = createFakeOctokit();
  const inline = [finding(), finding({ line: 12 })];

  await post(octokit, {
    selection: {
      ...selection({ inline }),
      fingerprints: ["aaaaaaaaaaaaaaaa", null],
    },
  });

  const [first, second] = octokit.reviews[0].comments;
  assert.equal(first.body.split("\n")[1], fingerprintLine("aaaaaaaaaaaaaaaa"));
  assert.ok(!second.body.includes("reviewops-fingerprint"));
});

test("posts comments without fingerprints when the selection has none", async () => {
  const octokit = createFakeOctokit();

  await post(octokit);

  assert.ok(!octokit.reviews[0].comments[0].body.includes("fingerprint"));
});

test("the second review lists the findings and carries their fingerprints", async () => {
  const octokit = createFakeOctokit([], {
    createReview: (parameters, index) =>
      index === 0 ? apiFailure(422) : { status: 200, data: { id: 7 } },
  });

  await post(octokit, {
    selection: {
      ...selection({ inline: [finding()] }),
      fingerprints: [FINGERPRINT],
    },
  });

  assert.equal(octokit.reviews.length, 2);
  assert.equal(octokit.reviews[1].comments, undefined);
  assert.ok(
    octokit.reviews[1].body.startsWith(
      `${REVIEW_MARKER}
${fingerprintLine(FINGERPRINT)}

`,
    ),
  );
});

test("the review text names the commit it starts at", () => {
  const body = bodyWith({ since: `abcdef1${"0".repeat(33)}` });

  assert.match(
    body,
    /^<!-- reviewops -->\n\n### ReviewOps\n\nReviewed the changes since `abcdef1`\.\n\n/,
  );
});

test("the review text says nothing about a start when everything was checked", () => {
  assert.ok(!bodyWith({}).includes("Reviewed the changes since"));
});

test("posts the review with the start of the range", async () => {
  const octokit = createFakeOctokit();

  await post(octokit, { since: "d".repeat(40) });

  assert.match(
    octokit.reviews[0].body,
    /Reviewed the changes since `ddddddd`\./,
  );
});

test("the review text carries the fingerprints of the findings in its text", async () => {
  const octokit = createFakeOctokit();

  await post(octokit, {
    selection: {
      ...selection({ unplaced: [finding(), finding({ line: 3 })] }),
      unplacedFingerprints: ["aaaaaaaaaaaaaaaa", null],
    },
  });

  assert.ok(
    octokit.reviews[0].body.startsWith(
      `${REVIEW_MARKER}
${fingerprintLine("aaaaaaaaaaaaaaaa")}

### ReviewOps`,
    ),
  );
});

test("an incomplete review says so right below the marker", async () => {
  const octokit = createFakeOctokit();

  await post(octokit, { incomplete: true });

  assert.ok(
    octokit.reviews[0].body.startsWith(
      `${REVIEW_MARKER}
${INCOMPLETE_LINE}

### ReviewOps`,
    ),
  );
  // Not a line of a comment: only a review is incomplete.
  assert.ok(!octokit.reviews[0].comments[0].body.includes(INCOMPLETE_LINE));
});

test("a complete review has no such line", async () => {
  const octokit = createFakeOctokit();

  await post(octokit);

  assert.ok(!octokit.reviews[0].body.includes(INCOMPLETE_LINE));
});

test("text of the model cannot add a line below the marker", () => {
  const body = reviewBody({
    model: "gpt-4.1",
    summaries: [
      `${INCOMPLETE_LINE}
${fingerprintLine(FINGERPRINT)}`,
    ],
    inline: [],
    listed: [],
    overLimit: 0,
    maxComments: 10,
    skipped: [],
  });

  assert.ok(
    body.startsWith(`${REVIEW_MARKER}

### ReviewOps`),
  );
  assert.ok(!body.includes(INCOMPLETE_LINE));
  assert.ok(!body.includes("reviewops-fingerprint"));
});
