// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Probe.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261005120000_AddUsers")]
    partial class AddUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity("Probe.User", b =>
            {
                b.Property<int>("Id");
                b.Property<string>("Email");
                b.HasKey("Id");
                b.ToTable("Users");
            });
        }
    }
}
