// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace Probe.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity("Probe.User", b =>
            {
                b.Property<int>("Id");
                b.Property<string>("Email");
                b.HasKey("Id");
                b.ToTable("Users");
            });
        }
    }
}
