import { SEVERITIES } from "../ai/schema.js";
import { describeApiError } from "./api-error.js";
import { inlineCode, modelMarkdown, plainText } from "./markdown.js";

/**
 * Marks every comment and every review text of this action. It always
 * stands at the very start of a body; text from the model can never put it
 * there, and its `<` is escaped anywhere else.
 */
export const REVIEW_MARKER = "<!-- reviewops -->";

/**
 * The longest body this action sends. GitHub accepts 65536 characters.
 */
export const MAX_BODY_CHARS = 60000;

/** File names listed in the review text; the rest is counted. */
export const MAX_LISTED_FILES = 20;

// A longer path is cut in the review text. GitHub allows much longer paths,
// and the list is meant to be read.
const MAX_PATH_CHARS = 200;

// The texts of a finding are cut before they are rendered, so the marker and
// the AI label always stay in a comment. Rendering makes a text at most
// seven times longer (an invisible character becomes an escaped
// backslash-u code), so even then a comment stays below MAX_BODY_CHARS.
export const MAX_TITLE_CHARS = 200;
export const MAX_TEXT_CHARS = 4000;

const SEVERITY_LABELS = Object.freeze({
  critical: "🔴 Critical",
  major: "🟠 Major",
  minor: "🟡 Minor",
  info: "🔵 Info",
});

// Between two blocks of a body: an empty line.
const BLOCK_SEPARATOR = "\n\n";

// What a status means when a review is posted.
const POST_REVIEW_HINTS = Object.freeze({
  403: "The token may not post a review. Give the workflow the permission `pull-requests: write` under `permissions`.",
  404: "The pull request was not found, or the token has no access to the repository.",
  422: "GitHub did not accept the review. Turn on debug logging to see the answer from GitHub.",
});

/**
 * The line that marks a text as written by an AI model.
 *
 * @param {string} model A name that `parseModel()` returned.
 * @returns {string}
 */
export function aiLabel(model) {
  return `<sub>AI-generated by ReviewOps (${plainText(model)}). Check it before you act on it.</sub>`;
}

/**
 * The line that carries the fingerprint of the commented line. It is the
 * second line of an inline comment, right below the marker. `readHistory()`
 * reads it back with a strict pattern.
 *
 * @param {string} fingerprint 16 hex characters from `lineFingerprint()`.
 * @returns {string}
 */
export const fingerprintLine = (fingerprint) =>
  `<!-- reviewops-fingerprint: ${fingerprint} -->`;

/**
 * The line that marks a review as not complete: files were left out or a
 * request failed. It stands right below the marker. A later run does not
 * start at such a review, so what was missed is checked again.
 */
export const INCOMPLETE_LINE = "<!-- reviewops-incomplete -->";

/**
 * The first block of a body: the marker, then the line for an incomplete
 * review and the fingerprints of the findings that stand in the text. A later
 * run reads only these lines, directly below the marker, never the text of
 * the model further down.
 *
 * @param {{ incomplete: boolean, fingerprints: (string | null)[] }} options
 * @returns {string}
 */
function reviewHead({ incomplete, fingerprints }) {
  return [
    REVIEW_MARKER,
    ...(incomplete ? [INCOMPLETE_LINE] : []),
    ...fingerprints.filter(Boolean).map(fingerprintLine),
  ].join("\n");
}

/**
 * The body of one inline comment.
 *
 * @param {import("../ai/schema.js").Finding} finding
 * @param {string} model
 * @param {string | null} [fingerprint] Fingerprint of the commented line.
 * @returns {string}
 */
export function commentBody(finding, model, fingerprint = null) {
  const head = reviewHead({ incomplete: false, fingerprints: [fingerprint] });
  return [head, findingMarkdown(finding), "---", aiLabel(model)].join("\n\n");
}

/**
 * The text of the review.
 *
 * @param {object} options
 * @param {string} options.model
 * @param {string[]} options.summaries The summaries of the requests.
 * @param {import("../ai/schema.js").Finding[]} options.inline Findings that
 *   are posted as inline comments; only counted here.
 * @param {import("../ai/schema.js").Finding[]} options.listed Findings whose
 *   whole text stands in the review text.
 * @param {number} options.overLimit Findings left out by `max-comments`.
 * @param {number} options.maxComments
 * @param {{ path: string, reason: string }[]} options.skipped Files that
 *   were not reviewed, with the reason.
 * @param {boolean} [options.fallback] GitHub rejected the inline comments,
 *   so every finding is listed.
 * @param {boolean} [options.incomplete] Not everything was reviewed.
 * @param {(string | null)[]} [options.fingerprints] Fingerprints of the
 *   findings in `listed`, in their order.
 * @param {string | null} [options.since] The commit this review starts at,
 *   when only the changes since an earlier review were checked. It must be a
 *   full commit SHA.
 * @returns {string} At most {@link MAX_BODY_CHARS} characters.
 */
export function reviewBody({
  model,
  summaries,
  inline,
  listed,
  overLimit,
  maxComments,
  skipped,
  fallback = false,
  incomplete = false,
  fingerprints = [],
  since = null,
}) {
  const shown = [...inline, ...listed];
  const counts = SEVERITIES.map(
    (severity) =>
      `${shown.filter((finding) => finding.severity === severity).length} ${severity}`,
  ).join(", ");

  const head = [reviewHead({ incomplete, fingerprints }), "### ReviewOps"];
  // The SHA was checked when it was read: it is 40 hex characters.
  if (since !== null) {
    head.push(`Reviewed the changes since ${inlineCode(since.slice(0, 7))}.`);
  }
  const findingsLine = [`**Findings:** ${shown.length} (${counts}).`];
  if (overLimit > 0) {
    findingsLine.push(
      `${overLimit} more findings are not shown (\`max-comments\`: ${maxComments}).`,
    );
  }

  const listHeading = fallback
    ? "#### Findings\n\nGitHub did not accept the inline comments, so every finding is listed here."
    : "#### Findings without a line in the diff\n\nThese findings point at a line that cannot carry a comment.";

  const tail = [];
  if (skipped.length > 0) tail.push(skippedList(skipped));
  tail.push("---", aiLabel(model));

  // Every block is rendered once. Cutting only counts lengths and joins the
  // chosen blocks at the end, so it stays linear in the number of blocks.
  const summaryBlocks = summaries.map(modelMarkdown);
  const findingBlocks = listed.map(locatedFinding);
  const summaryLengths = prefixLengths(summaryBlocks);
  const findingLengths = prefixLengths(findingBlocks);

  const notesFor = (summaryCount, findingCount) => {
    const result = [];
    if (summaryCount < summaries.length) {
      result.push(
        `${summaries.length - summaryCount} summaries are left out: they do not fit into one review.`,
      );
    }
    if (findingCount < listed.length) {
      result.push(
        `${listed.length - findingCount} more findings are not shown: they do not fit into one review.`,
      );
    }
    return result;
  };
  const fixed = [
    ...head,
    findingsLine.join(" "),
    ...(listed.length > 0 ? [listHeading] : []),
    ...tail,
  ];
  const fixedLength = fixed.reduce((sum, block) => sum + block.length, 0);
  const lengthOf = (summaryCount, findingCount) => {
    const notes = notesFor(summaryCount, findingCount);
    const blocks = fixed.length + summaryCount + findingCount + notes.length;
    return (
      fixedLength +
      summaryLengths[summaryCount] +
      findingLengths[findingCount] +
      notes.reduce((sum, note) => sum + note.length, 0) +
      (blocks - 1) * BLOCK_SEPARATOR.length
    );
  };

  // Too long a text is cut where it hurts least: first the summaries, which
  // grow with the number of requests, then findings from the end.
  let summaryCount = summaries.length;
  let findingCount = listed.length;
  while (
    lengthOf(summaryCount, findingCount) > MAX_BODY_CHARS &&
    summaryCount > 0
  ) {
    summaryCount -= 1;
  }
  while (
    lengthOf(summaryCount, findingCount) > MAX_BODY_CHARS &&
    findingCount > 0
  ) {
    findingCount -= 1;
  }

  const blocks = [...head, ...summaryBlocks.slice(0, summaryCount)];
  blocks.push(findingsLine.join(" "));
  if (listed.length > 0) {
    blocks.push(listHeading, ...findingBlocks.slice(0, findingCount));
  }
  blocks.push(...notesFor(summaryCount, findingCount), ...tail);
  return capLength(blocks.join(BLOCK_SEPARATOR));
}

/** `result[n]` is the summed length of the first `n` blocks. */
function prefixLengths(blocks) {
  const result = [0];
  for (const block of blocks) result.push(result.at(-1) + block.length);
  return result;
}

/**
 * Posts the review of a pull request: one review of the type COMMENT with
 * every inline comment. When GitHub rejects the inline comments (HTTP 422),
 * a second review without them lists every finding in its text.
 *
 * Nothing in here writes to the log: the texts come from the model.
 *
 * @param {object} options
 * @param {ReturnType<typeof import("@actions/github").getOctokit>} options.octokit
 * @param {{ owner: string, repo: string, pullNumber: number, headSha: string }} options.pullRequest
 * @param {string} options.model
 * @param {string[]} options.summaries
 * @param {{
 *   inline: import("../ai/schema.js").Finding[],
 *   fingerprints?: (string | null)[],
 *   unplaced: import("../ai/schema.js").Finding[],
 *   unplacedFingerprints?: (string | null)[],
 *   dropped: { overLimit: number },
 * }} options.selection What `selectFindings()` returned.
 * @param {number} options.maxComments
 * @param {{ path: string, reason: string }[]} options.skipped
 * @param {boolean} [options.incomplete] Files were left out or a request
 *   failed: a later run must not start at this review.
 * @param {string | null} [options.since] The commit of the earlier review
 *   when only the changes since then were checked.
 * @returns {Promise<{ reviewId: number | null, inlineComments: number, fallback: boolean }>}
 * @throws {Error} When GitHub accepts no review, with a message that says
 *   what to do.
 */
export async function postReview({
  octokit,
  pullRequest,
  model,
  summaries,
  selection,
  maxComments,
  skipped,
  incomplete = false,
  since = null,
}) {
  const {
    inline,
    unplaced,
    dropped,
    fingerprints = [],
    unplacedFingerprints = [],
  } = selection;
  const common = {
    model,
    summaries,
    overLimit: dropped.overLimit,
    maxComments,
    skipped,
    incomplete,
    since,
  };
  const request = (body, comments) =>
    octokit.rest.pulls.createReview({
      owner: pullRequest.owner,
      repo: pullRequest.repo,
      pull_number: pullRequest.pullNumber,
      commit_id: pullRequest.headSha,
      // The only type this action ever posts: it never approves and never
      // blocks a merge.
      event: "COMMENT",
      body,
      ...(comments.length > 0 ? { comments } : {}),
    });

  const comments = inline.map((finding, index) => ({
    path: finding.path,
    line: finding.line,
    side: "RIGHT",
    body: commentBody(finding, model, fingerprints[index] ?? null),
  }));

  try {
    const response = await request(
      reviewBody({
        ...common,
        inline,
        listed: unplaced,
        fingerprints: unplacedFingerprints,
      }),
      comments,
    );
    return {
      reviewId: reviewIdOf(response),
      inlineComments: comments.length,
      fallback: false,
    };
  } catch (error) {
    if (error?.status !== 422 || comments.length === 0) {
      throw describeApiError(error, POST_REVIEW_HINTS);
    }
  }

  try {
    const response = await request(
      reviewBody({
        ...common,
        inline: [],
        listed: [...inline, ...unplaced],
        fingerprints: [...fingerprints, ...unplacedFingerprints],
        fallback: true,
      }),
      [],
    );
    return {
      reviewId: reviewIdOf(response),
      inlineComments: 0,
      fallback: true,
    };
  } catch (error) {
    throw describeApiError(error, POST_REVIEW_HINTS);
  }
}

// The address of the GitHub server: github.com or GitHub Enterprise.
const SERVER_URL = /^https:\/\/[A-Za-z0-9.-]{1,253}(?::\d{1,5})?$/;

/**
 * The address of the GitHub server of this run. `@actions/github` takes it
 * from GITHUB_SERVER_URL; anything that does not look like an address of a
 * server falls back to github.com.
 *
 * @param {unknown} value `context.serverUrl`
 * @returns {string}
 */
export function serverUrlOf(value) {
  return typeof value === "string" && SERVER_URL.test(value)
    ? value
    : "https://github.com";
}

/**
 * The address of a review, built from checked values only.
 *
 * @param {string} serverUrl
 * @param {{ owner: string, repo: string, pullNumber: number }} pullRequest
 * @param {number} reviewId
 * @returns {string}
 */
export function reviewUrl(serverUrl, { owner, repo, pullNumber }, reviewId) {
  return `${serverUrl}/${owner}/${repo}/pull/${pullNumber}#pullrequestreview-${reviewId}`;
}

/** The id of a created review, or `null` when the answer has none. */
function reviewIdOf(response) {
  const id = response?.data?.id;
  return Number.isSafeInteger(id) && id > 0 ? id : null;
}

/** Severity, category, title, comment and suggestion of a finding. */
function findingMarkdown(finding, location = "") {
  const title = shorten(
    finding.title.replace(/\s+/g, " ").trim(),
    MAX_TITLE_CHARS,
  );
  return [
    `**${SEVERITY_LABELS[finding.severity]}** · ${inlineCode(finding.category)}${location}`,
    `**${plainText(title)}**`,
    modelMarkdown(shorten(finding.comment, MAX_TEXT_CHARS)),
    "**Suggestion**",
    modelMarkdown(shorten(finding.suggestion, MAX_TEXT_CHARS)),
  ].join("\n\n");
}

/** Cuts a text after `max` characters, without splitting a surrogate pair. */
function shorten(text, max) {
  if (text.length <= max) return text;
  // A high surrogate at the end would lose the half that follows it.
  const last = text.charCodeAt(max - 1);
  const end = last >= 0xd800 && last <= 0xdbff ? max - 1 : max;
  return `${text.slice(0, end)}…`;
}

/** A finding in the review text, with the place it points at. */
function locatedFinding(finding) {
  return findingMarkdown(
    finding,
    ` · ${pathCode(finding.path)}, line ${finding.line}`,
  );
}

/** The files that were not reviewed, the first ones by name. */
function skippedList(skipped) {
  const lines = skipped
    .slice(0, MAX_LISTED_FILES)
    .map(({ path, reason }) => `- ${pathCode(path)}: ${plainText(reason)}`);
  if (skipped.length > MAX_LISTED_FILES) {
    lines.push(`- and ${skipped.length - MAX_LISTED_FILES} more files`);
  }
  return [`#### Files not reviewed (${skipped.length})`, lines.join("\n")].join(
    "\n\n",
  );
}

/** A file name as inline code. File names come from the pull request. */
function pathCode(path) {
  const name =
    path.length > MAX_PATH_CHARS ? `${path.slice(0, MAX_PATH_CHARS)}…` : path;
  return inlineCode(name);
}

/** The last guard: a body is never longer than GitHub accepts. */
function capLength(text) {
  return text.length > MAX_BODY_CHARS
    ? `${text.slice(0, MAX_BODY_CHARS - 1)}…`
    : text;
}
