import { SEVERITIES } from "../ai/schema.js";
import { describeApiError } from "./api-error.js";
import { inlineCode, modelMarkdown, plainText } from "./markdown.js";

/**
 * Marks every comment and every review text of this action. It always
 * stands at the very start of a body; text from the model can never put it
 * there, and its `<` is escaped anywhere else.
 */
export const REVIEW_MARKER = "<!-- reviewops -->";

/**
 * The longest body this action sends. GitHub accepts 65536 characters.
 */
export const MAX_BODY_CHARS = 60000;

/** File names listed in the review text; the rest is counted. */
export const MAX_LISTED_FILES = 20;

// A longer path is cut in the review text. GitHub allows much longer paths,
// and the list is meant to be read.
const MAX_PATH_CHARS = 200;

const SEVERITY_LABELS = Object.freeze({
  critical: "🔴 Critical",
  major: "🟠 Major",
  minor: "🟡 Minor",
  info: "🔵 Info",
});

// What a status means when a review is posted.
const POST_REVIEW_HINTS = Object.freeze({
  403: "The token may not post a review. Give the workflow the permission `pull-requests: write` under `permissions`.",
  404: "The pull request was not found, or the token has no access to the repository.",
  422: "GitHub did not accept the review. Turn on debug logging to see the answer from GitHub.",
});

/**
 * The line that marks a text as written by an AI model.
 *
 * @param {string} model A name that `parseModel()` returned.
 * @returns {string}
 */
export function aiLabel(model) {
  return `<sub>AI-generated by ReviewOps (${plainText(model)}). Check it before you act on it.</sub>`;
}

/**
 * The body of one inline comment.
 *
 * @param {import("../ai/schema.js").Finding} finding
 * @param {string} model
 * @returns {string}
 */
export function commentBody(finding, model) {
  return capLength(
    [REVIEW_MARKER, findingMarkdown(finding), "---", aiLabel(model)].join(
      "\n\n",
    ),
  );
}

/**
 * The text of the review.
 *
 * @param {object} options
 * @param {string} options.model
 * @param {string[]} options.summaries The summaries of the requests.
 * @param {import("../ai/schema.js").Finding[]} options.inline Findings that
 *   are posted as inline comments; only counted here.
 * @param {import("../ai/schema.js").Finding[]} options.listed Findings whose
 *   whole text stands in the review text.
 * @param {number} options.overLimit Findings left out by `max-comments`.
 * @param {number} options.maxComments
 * @param {{ path: string, reason: string }[]} options.skipped Files that
 *   were not reviewed, with the reason.
 * @param {boolean} [options.fallback] GitHub rejected the inline comments,
 *   so every finding is listed.
 * @returns {string} At most {@link MAX_BODY_CHARS} characters.
 */
export function reviewBody({
  model,
  summaries,
  inline,
  listed,
  overLimit,
  maxComments,
  skipped,
  fallback = false,
}) {
  const shown = [...inline, ...listed];
  const counts = SEVERITIES.map(
    (severity) =>
      `${shown.filter((finding) => finding.severity === severity).length} ${severity}`,
  ).join(", ");

  const head = [REVIEW_MARKER, "### ReviewOps"];
  const findingsLine = [`**Findings:** ${shown.length} (${counts}).`];
  if (overLimit > 0) {
    findingsLine.push(
      `${overLimit} more findings are not shown (\`max-comments\`: ${maxComments}).`,
    );
  }

  const listHeading = fallback
    ? "#### Findings\n\nGitHub did not accept the inline comments, so every finding is listed here."
    : "#### Findings without a line in the diff\n\nThese findings point at a line that cannot carry a comment.";

  const tail = [];
  if (skipped.length > 0) tail.push(skippedList(skipped));
  tail.push("---", aiLabel(model));

  const compose = (summaryCount, findingCount, notes) => {
    const blocks = [...head];
    blocks.push(...summaries.slice(0, summaryCount).map(modelMarkdown));
    blocks.push(findingsLine.join(" "));
    if (listed.length > 0) {
      blocks.push(listHeading);
      blocks.push(
        ...listed
          .slice(0, findingCount)
          .map((finding) => locatedFinding(finding)),
      );
    }
    blocks.push(...notes);
    blocks.push(...tail);
    return blocks.join("\n\n");
  };

  // Too long a text is cut where it hurts least: first the summaries, which
  // grow with the number of requests, then findings from the end.
  let summaryCount = summaries.length;
  let findingCount = listed.length;
  const notes = () => {
    const result = [];
    if (summaryCount < summaries.length) {
      result.push(
        `${summaries.length - summaryCount} summaries are left out: they do not fit into one review.`,
      );
    }
    if (findingCount < listed.length) {
      result.push(
        `${listed.length - findingCount} more findings are not shown: they do not fit into one review.`,
      );
    }
    return result;
  };
  let text = compose(summaryCount, findingCount, notes());
  while (text.length > MAX_BODY_CHARS && summaryCount > 0) {
    summaryCount -= 1;
    text = compose(summaryCount, findingCount, notes());
  }
  while (text.length > MAX_BODY_CHARS && findingCount > 0) {
    findingCount -= 1;
    text = compose(summaryCount, findingCount, notes());
  }
  return capLength(text);
}

/**
 * Posts the review of a pull request: one review of the type COMMENT with
 * every inline comment. When GitHub rejects the inline comments (HTTP 422),
 * a second review without them lists every finding in its text.
 *
 * Nothing in here writes to the log: the texts come from the model.
 *
 * @param {object} options
 * @param {ReturnType<typeof import("@actions/github").getOctokit>} options.octokit
 * @param {{ owner: string, repo: string, pullNumber: number, headSha: string }} options.pullRequest
 * @param {string} options.model
 * @param {string[]} options.summaries
 * @param {{
 *   inline: import("../ai/schema.js").Finding[],
 *   unplaced: import("../ai/schema.js").Finding[],
 *   dropped: { overLimit: number },
 * }} options.selection What `selectFindings()` returned.
 * @param {number} options.maxComments
 * @param {{ path: string, reason: string }[]} options.skipped
 * @returns {Promise<{ reviewId: number | null, inlineComments: number, fallback: boolean }>}
 * @throws {Error} When GitHub accepts no review, with a message that says
 *   what to do.
 */
export async function postReview({
  octokit,
  pullRequest,
  model,
  summaries,
  selection,
  maxComments,
  skipped,
}) {
  const { inline, unplaced, dropped } = selection;
  const common = {
    model,
    summaries,
    overLimit: dropped.overLimit,
    maxComments,
    skipped,
  };
  const request = (body, comments) =>
    octokit.rest.pulls.createReview({
      owner: pullRequest.owner,
      repo: pullRequest.repo,
      pull_number: pullRequest.pullNumber,
      commit_id: pullRequest.headSha,
      // The only type this action ever posts: it never approves and never
      // blocks a merge.
      event: "COMMENT",
      body,
      ...(comments.length > 0 ? { comments } : {}),
    });

  const comments = inline.map((finding) => ({
    path: finding.path,
    line: finding.line,
    side: "RIGHT",
    body: commentBody(finding, model),
  }));

  try {
    const response = await request(
      reviewBody({ ...common, inline, listed: unplaced }),
      comments,
    );
    return {
      reviewId: reviewIdOf(response),
      inlineComments: comments.length,
      fallback: false,
    };
  } catch (error) {
    if (error?.status !== 422 || comments.length === 0) {
      throw describeApiError(error, POST_REVIEW_HINTS);
    }
  }

  try {
    const response = await request(
      reviewBody({
        ...common,
        inline: [],
        listed: [...inline, ...unplaced],
        fallback: true,
      }),
      [],
    );
    return {
      reviewId: reviewIdOf(response),
      inlineComments: 0,
      fallback: true,
    };
  } catch (error) {
    throw describeApiError(error, POST_REVIEW_HINTS);
  }
}

// The address of the GitHub server: github.com or GitHub Enterprise.
const SERVER_URL = /^https:\/\/[A-Za-z0-9.-]{1,253}(?::\d{1,5})?$/;

/**
 * The address of the GitHub server of this run. `@actions/github` takes it
 * from GITHUB_SERVER_URL; anything that does not look like an address of a
 * server falls back to github.com.
 *
 * @param {unknown} value `context.serverUrl`
 * @returns {string}
 */
export function serverUrlOf(value) {
  return typeof value === "string" && SERVER_URL.test(value)
    ? value
    : "https://github.com";
}

/**
 * The address of a review, built from checked values only.
 *
 * @param {string} serverUrl
 * @param {{ owner: string, repo: string, pullNumber: number }} pullRequest
 * @param {number} reviewId
 * @returns {string}
 */
export function reviewUrl(serverUrl, { owner, repo, pullNumber }, reviewId) {
  return `${serverUrl}/${owner}/${repo}/pull/${pullNumber}#pullrequestreview-${reviewId}`;
}

/** The id of a created review, or `null` when the answer has none. */
function reviewIdOf(response) {
  const id = response?.data?.id;
  return Number.isSafeInteger(id) && id > 0 ? id : null;
}

/** Severity, category, title, comment and suggestion of a finding. */
function findingMarkdown(finding, location = "") {
  const title = plainText(finding.title.replace(/\s+/g, " ").trim());
  return [
    `**${SEVERITY_LABELS[finding.severity]}** · ${inlineCode(finding.category)}${location}`,
    `**${title}**`,
    modelMarkdown(finding.comment),
    "**Suggestion**",
    modelMarkdown(finding.suggestion),
  ].join("\n\n");
}

/** A finding in the review text, with the place it points at. */
function locatedFinding(finding) {
  return findingMarkdown(
    finding,
    ` · ${pathCode(finding.path)}, line ${finding.line}`,
  );
}

/** The files that were not reviewed, the first ones by name. */
function skippedList(skipped) {
  const lines = skipped
    .slice(0, MAX_LISTED_FILES)
    .map(({ path, reason }) => `- ${pathCode(path)}: ${plainText(reason)}`);
  if (skipped.length > MAX_LISTED_FILES) {
    lines.push(`- and ${skipped.length - MAX_LISTED_FILES} more files`);
  }
  return [`#### Files not reviewed (${skipped.length})`, lines.join("\n")].join(
    "\n\n",
  );
}

/** A file name as inline code. File names come from the pull request. */
function pathCode(path) {
  const name =
    path.length > MAX_PATH_CHARS ? `${path.slice(0, MAX_PATH_CHARS)}…` : path;
  return inlineCode(name);
}

/** The last guard: a body is never longer than GitHub accepts. */
function capLength(text) {
  return text.length > MAX_BODY_CHARS
    ? `${text.slice(0, MAX_BODY_CHARS - 1)}…`
    : text;
}
